[package]
name = "play"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustpython-vm = { version = "0.3.0", features = ["freeze-stdlib"] }
#rustpython-stdlib = "0.3.0"
malachite-bigint = { version = "=0.1.0" }
malachite-q = "=0.3.2"
malachite-base = "=0.3.2"
zip-extract = "0.1.2"